// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQ5XhYgidGTgPE3skRQSkB4SCgx-7MTk',
    appId: '1:276743700978:web:ec7fc504267c35e2cbab6b',
    messagingSenderId: '276743700978',
    projectId: 'restaurant-app-454ee',
    authDomain: 'restaurant-app-454ee.firebaseapp.com',
    storageBucket: 'restaurant-app-454ee.appspot.com',
    measurementId: 'G-HP7MKZ7QFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlMTejDW_PtPjCPt-NrAtOKtawwzaE-E',
    appId: '1:276743700978:android:814bdf7b9e41fa75cbab6b',
    messagingSenderId: '276743700978',
    projectId: 'restaurant-app-454ee',
    storageBucket: 'restaurant-app-454ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Rz8vhxX5-sX4Afr3DGX4eQBQELE1-dg',
    appId: '1:276743700978:ios:152fe5742ae608e7cbab6b',
    messagingSenderId: '276743700978',
    projectId: 'restaurant-app-454ee',
    storageBucket: 'restaurant-app-454ee.appspot.com',
    iosClientId: '276743700978-7350ink15isccqpecloijos188lm4tve.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp',
  );
}
